import * as m from 'zigbee-herdsman-converters/lib/modernExtend';
import * as exposes_1 from 'zigbee-herdsman-converters/lib/exposes';
import * as reporting from 'zigbee-herdsman-converters/lib/reporting';
import * as utils_1 from 'zigbee-herdsman-converters/lib/utils';
import * as logger from 'zigbee-herdsman-converters/lib/logger';

const attrSwitchType = 0xf000;
const attrSwitchDecoupled = 0xf001;

const attrDeviceModelNumber = 0xf002;

const attrDoorDelayOn = 0xf003;
const attrDoorDelayOff = 0xf004;
const attrDoorOnCmdOff = 0xf005;
const attrDoorOffCmdOff = 0xf006;

const attrSceneId = 0xf000;
const attrGroupId = 0xf001;

function localActionExtend(args = {}) {
    const { localAction = ["hold", "single", "double", "triple", "quadruple", "quintuple", "release"], 
            bind = true,
            reporting = true, 
            reportingConfig = {"min": 10, "max": 0, change: 1},
            endpointNames = undefined } = args;
    let actions = localAction;
    if (endpointNames) {
        actions = localAction.flatMap((c) => endpointNames.map((e) => `${c}_${e}`));
    }
    const exposes = [exposes_1.presets.enum("action", exposes_1.access.STATE, actions)];
    const attribute = "presentValue";

    
    const actionPayloadLookup = {
      0: "hold",
      1: "single",
      2: "double",
      3: "triple",
      4: "quadruple",
      5: "quintuple",
      255: "release",
    };

    const fromZigbee = [
        {
            cluster: "genMultistateInput",
            type: ["attributeReport", "readResponse"],
            convert: (model, msg, publish, options, meta) => {
                if ((0, utils_1.hasAlreadyProcessedMessage)(msg, model))
                    return;
                const data = msg.data;
                //logger.logger.info('msg.data: ' + data[attribute]);
                if (data[attribute] == 300)
                    return "N/A";
                const payload = { action: (0, utils_1.postfixWithEndpointName)(actionPayloadLookup[data[attribute]], msg, model, meta) };
                return payload;
            },
        },
    ];
    const result = { exposes, fromZigbee, isModernExtend: true };
    if (reporting)
        result.configure = [m.setupConfigureForBinding("genMultistateInput", "input", endpointNames),
                            m.setupConfigureForReporting("genMultistateInput", attribute, {config: reportingConfig, access: exposes_1.access.GET, endpointNames})];
    else if (bind) result.configure = [m.setupConfigureForBinding("genMultistateInput", "input", endpointNames)];
        
    return result;

}

export default {
        zigbeeModel: ["FreePad-20K-SlD"],
        model: "FreePad-20K-SlD",
        vendor: "Slacky-DIY",
        description: "DIY 20 buttons keypad",
        extend: [
            m.deviceAddCustomCluster("genOnOffSwitchCfg", {
                name: "genOnOffSwitchCfg",
                ID: 0x0007,
                attributes: {
                    customSwitchType: {
                        name: "customSwitchType",
                        ID: attrSwitchType,
                        type: 0x30,
                        write: true,
                        max: 0xff,
                    },
                    customDeviceModelNumber: {
                        name: "customDeviceModelNumber",
                        ID: attrDeviceModelNumber,
                        type: 0x30,
                        write: true,
                        max: 0xff,
                    },
                },
                commands: {},
                commandsResponse: {},
            }),
            m.deviceAddCustomCluster("genLevelCtrl", {
                name: "genLevelCtrl",
                ID: 0x0008,
                attributes: {
                    minLevel: {
                        name: "minLevel",
                        ID: 0x0002,
                        type: 0x20,
                        write: true,
                        max: 0xff,
                    },
                    maxLevel: {
                        name: "maxLevel",
                        ID: 0x0003,
                        type: 0x20,
                        write: true,
                        max: 0xff,
                    },
                },
                commands: {},
                commandsResponse: {},
            }),
            m.deviceAddCustomCluster("genScenes", {
                name: "genScenes",
                ID: 0x0005,
                attributes: {
                    customSceneId: {
                        name: "customSceneId",
                        ID: attrSceneId,
                        type: 0x20,
                        write: true,
                        max: 0xff,
                    },
                    customGroupId: {
                        name: "customGroupId",
                        ID: attrGroupId,
                        type: 0x21,
                        write: true,
                        max: 0xffff,
                    },
                },
                commands: {},
                commandsResponse: {},
            }),
            m.deviceEndpoints({
                endpoints: {
                    "1": 1,
                    "2": 2,
                    "3": 3,
                    "4": 4,
                    "5": 5,
                    "6": 6,
                    "7": 7,
                    "8": 8,
                    "9": 9,
                    "10": 10,
                    "11": 11,
                    "12": 12,
                    "13": 13,
                    "14": 14,
                    "15": 15,
                    "16": 16,
                    "17": 17,
                    "18": 18,
                    "19": 19,
                    "20": 20,
                },
            }),
            m.battery({
                percentageReportingConfig: {min: 3600, max: 14400, change: 0},
            }),
            m.commandsOnOff({
                endpointNames: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            }),
            localActionExtend({
                endpointNames: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
                reporting: false,
            }),
            m.commandsLevelCtrl({
                endpointNames: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            }),
            m.enumLookup({
                name: "switch_actions",
                endpointName: "1",
                lookup: {
                    off: 0,
                    on: 1,
                    toggle: 2,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "switchActions",
                description: "Actions switch",
            }),
            m.enumLookup({
                name: "switch_actions",
                endpointName: "2",
                lookup: {
                    off: 0,
                    on: 1,
                    toggle: 2,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "switchActions",
                description: "Actions switch",
            }),
            m.enumLookup({
                name: "switch_actions",
                endpointName: "3",
                lookup: {
                    off: 0,
                    on: 1,
                    toggle: 2,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "switchActions",
                description: "Actions switch",
            }),
            m.enumLookup({
                name: "switch_actions",
                endpointName: "4",
                lookup: {
                    off: 0,
                    on: 1,
                    toggle: 2,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "switchActions",
                description: "Actions switch",
            }),
            m.enumLookup({
                name: "switch_actions",
                endpointName: "5",
                lookup: {
                    off: 0,
                    on: 1,
                    toggle: 2,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "switchActions",
                description: "Actions switch",
            }),
            m.enumLookup({
                name: "switch_actions",
                endpointName: "6",
                lookup: {
                    off: 0,
                    on: 1,
                    toggle: 2,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "switchActions",
                description: "Actions switch",
            }),
            m.enumLookup({
                name: "switch_actions",
                endpointName: "7",
                lookup: {
                    off: 0,
                    on: 1,
                    toggle: 2,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "switchActions",
                description: "Actions switch",
            }),
            m.enumLookup({
                name: "switch_actions",
                endpointName: "8",
                lookup: {
                    off: 0,
                    on: 1,
                    toggle: 2,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "switchActions",
                description: "Actions switch",
            }),
            m.enumLookup({
                name: "switch_actions",
                endpointName: "9",
                lookup: {
                    off: 0,
                    on: 1,
                    toggle: 2,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "switchActions",
                description: "Actions switch",
            }),
            m.enumLookup({
                name: "switch_actions",
                endpointName: "10",
                lookup: {
                    off: 0,
                    on: 1,
                    toggle: 2,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "switchActions",
                description: "Actions switch",
            }),
            m.enumLookup({
                name: "switch_actions",
                endpointName: "11",
                lookup: {
                    off: 0,
                    on: 1,
                    toggle: 2,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "switchActions",
                description: "Actions switch",
            }),
            m.enumLookup({
                name: "switch_actions",
                endpointName: "12",
                lookup: {
                    off: 0,
                    on: 1,
                    toggle: 2,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "switchActions",
                description: "Actions switch",
            }),
            m.enumLookup({
                name: "switch_actions",
                endpointName: "13",
                lookup: {
                    off: 0,
                    on: 1,
                    toggle: 2,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "switchActions",
                description: "Actions switch",
            }),
            m.enumLookup({
                name: "switch_actions",
                endpointName: "14",
                lookup: {
                    off: 0,
                    on: 1,
                    toggle: 2,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "switchActions",
                description: "Actions switch",
            }),
            m.enumLookup({
                name: "switch_actions",
                endpointName: "15",
                lookup: {
                    off: 0,
                    on: 1,
                    toggle: 2,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "switchActions",
                description: "Actions switch",
            }),
            m.enumLookup({
                name: "switch_actions",
                endpointName: "16",
                lookup: {
                    off: 0,
                    on: 1,
                    toggle: 2,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "switchActions",
                description: "Actions switch",
            }),
            m.enumLookup({
                name: "switch_actions",
                endpointName: "17",
                lookup: {
                    off: 0,
                    on: 1,
                    toggle: 2,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "switchActions",
                description: "Actions switch",
            }),
            m.enumLookup({
                name: "switch_actions",
                endpointName: "18",
                lookup: {
                    off: 0,
                    on: 1,
                    toggle: 2,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "switchActions",
                description: "Actions switch",
            }),
            m.enumLookup({
                name: "switch_actions",
                endpointName: "19",
                lookup: {
                    off: 0,
                    on: 1,
                    toggle: 2,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "switchActions",
                description: "Actions switch",
            }),
            m.enumLookup({
                name: "switch_actions",
                endpointName: "20",
                lookup: {
                    off: 0,
                    on: 1,
                    toggle: 2,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "switchActions",
                description: "Actions switch",
            }),
            m.enumLookup({
                name: "switch_type",
                endpointName: "1",
                lookup: {
                    toggle: 0,
                    momentary: 1,
                    multifunction: 2,
                    brightness_level: 3,
                    brightness_level_up: 4,
                    brightness_level_down: 5,
                    move_to_color_temperature: 6,
                    move_to_color_temperature_up: 7,
                    move_to_color_temperature_down: 8,
                    scene: 9,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "customSwitchType",
                description: "Switch type",
            }),
            m.enumLookup({
                name: "switch_type",
                endpointName: "2",
                lookup: {
                    toggle: 0,
                    momentary: 1,
                    multifunction: 2,
                    brightness_level: 3,
                    brightness_level_up: 4,
                    brightness_level_down: 5,
                    move_to_color_temperature: 6,
                    move_to_color_temperature_up: 7,
                    move_to_color_temperature_down: 8,
                    scene: 9,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "customSwitchType",
                description: "Switch type",
            }),
            m.enumLookup({
                name: "switch_type",
                endpointName: "3",
                lookup: {
                    toggle: 0,
                    momentary: 1,
                    multifunction: 2,
                    brightness_level: 3,
                    brightness_level_up: 4,
                    brightness_level_down: 5,
                    move_to_color_temperature: 6,
                    move_to_color_temperature_up: 7,
                    move_to_color_temperature_down: 8,
                    scene: 9,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "customSwitchType",
                description: "Switch type",
            }),
            m.enumLookup({
                name: "switch_type",
                endpointName: "4",
                lookup: {
                    toggle: 0,
                    momentary: 1,
                    multifunction: 2,
                    brightness_level: 3,
                    brightness_level_up: 4,
                    brightness_level_down: 5,
                    move_to_color_temperature: 6,
                    move_to_color_temperature_up: 7,
                    move_to_color_temperature_down: 8,
                    scene: 9,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "customSwitchType",
                description: "Switch type",
            }),
            m.enumLookup({
                name: "switch_type",
                endpointName: "5",
                lookup: {
                    toggle: 0,
                    momentary: 1,
                    multifunction: 2,
                    brightness_level: 3,
                    brightness_level_up: 4,
                    brightness_level_down: 5,
                    move_to_color_temperature: 6,
                    move_to_color_temperature_up: 7,
                    move_to_color_temperature_down: 8,
                    scene: 9,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "customSwitchType",
                description: "Switch type",
            }),
            m.enumLookup({
                name: "switch_type",
                endpointName: "6",
                lookup: {
                    toggle: 0,
                    momentary: 1,
                    multifunction: 2,
                    brightness_level: 3,
                    brightness_level_up: 4,
                    brightness_level_down: 5,
                    move_to_color_temperature: 6,
                    move_to_color_temperature_up: 7,
                    move_to_color_temperature_down: 8,
                    scene: 9,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "customSwitchType",
                description: "Switch type",
            }),
            m.enumLookup({
                name: "switch_type",
                endpointName: "7",
                lookup: {
                    toggle: 0,
                    momentary: 1,
                    multifunction: 2,
                    brightness_level: 3,
                    brightness_level_up: 4,
                    brightness_level_down: 5,
                    move_to_color_temperature: 6,
                    move_to_color_temperature_up: 7,
                    move_to_color_temperature_down: 8,
                    scene: 9,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "customSwitchType",
                description: "Switch type",
            }),
            m.enumLookup({
                name: "switch_type",
                endpointName: "8",
                lookup: {
                    toggle: 0,
                    momentary: 1,
                    multifunction: 2,
                    brightness_level: 3,
                    brightness_level_up: 4,
                    brightness_level_down: 5,
                    move_to_color_temperature: 6,
                    move_to_color_temperature_up: 7,
                    move_to_color_temperature_down: 8,
                    scene: 9,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "customSwitchType",
                description: "Switch type",
            }),
            m.enumLookup({
                name: "switch_type",
                endpointName: "9",
                lookup: {
                    toggle: 0,
                    momentary: 1,
                    multifunction: 2,
                    brightness_level: 3,
                    brightness_level_up: 4,
                    brightness_level_down: 5,
                    move_to_color_temperature: 6,
                    move_to_color_temperature_up: 7,
                    move_to_color_temperature_down: 8,
                    scene: 9,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "customSwitchType",
                description: "Switch type",
            }),
            m.enumLookup({
                name: "switch_type",
                endpointName: "10",
                lookup: {
                    toggle: 0,
                    momentary: 1,
                    multifunction: 2,
                    brightness_level: 3,
                    brightness_level_up: 4,
                    brightness_level_down: 5,
                    move_to_color_temperature: 6,
                    move_to_color_temperature_up: 7,
                    move_to_color_temperature_down: 8,
                    scene: 9,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "customSwitchType",
                description: "Switch type",
            }),
            m.enumLookup({
                name: "switch_type",
                endpointName: "11",
                lookup: {
                    toggle: 0,
                    momentary: 1,
                    multifunction: 2,
                    brightness_level: 3,
                    brightness_level_up: 4,
                    brightness_level_down: 5,
                    move_to_color_temperature: 6,
                    move_to_color_temperature_up: 7,
                    move_to_color_temperature_down: 8,
                    scene: 9,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "customSwitchType",
                description: "Switch type",
            }),
            m.enumLookup({
                name: "switch_type",
                endpointName: "12",
                lookup: {
                    toggle: 0,
                    momentary: 1,
                    multifunction: 2,
                    brightness_level: 3,
                    brightness_level_up: 4,
                    brightness_level_down: 5,
                    move_to_color_temperature: 6,
                    move_to_color_temperature_up: 7,
                    move_to_color_temperature_down: 8,
                    scene: 9,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "customSwitchType",
                description: "Switch type",
            }),
            m.enumLookup({
                name: "switch_type",
                endpointName: "13",
                lookup: {
                    toggle: 0,
                    momentary: 1,
                    multifunction: 2,
                    brightness_level: 3,
                    brightness_level_up: 4,
                    brightness_level_down: 5,
                    move_to_color_temperature: 6,
                    move_to_color_temperature_up: 7,
                    move_to_color_temperature_down: 8,
                    scene: 9,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "customSwitchType",
                description: "Switch type",
            }),
            m.enumLookup({
                name: "switch_type",
                endpointName: "14",
                lookup: {
                    toggle: 0,
                    momentary: 1,
                    multifunction: 2,
                    brightness_level: 3,
                    brightness_level_up: 4,
                    brightness_level_down: 5,
                    move_to_color_temperature: 6,
                    move_to_color_temperature_up: 7,
                    move_to_color_temperature_down: 8,
                    scene: 9,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "customSwitchType",
                description: "Switch type",
            }),
            m.enumLookup({
                name: "switch_type",
                endpointName: "15",
                lookup: {
                    toggle: 0,
                    momentary: 1,
                    multifunction: 2,
                    brightness_level: 3,
                    brightness_level_up: 4,
                    brightness_level_down: 5,
                    move_to_color_temperature: 6,
                    move_to_color_temperature_up: 7,
                    move_to_color_temperature_down: 8,
                    scene: 9,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "customSwitchType",
                description: "Switch type",
            }),
            m.enumLookup({
                name: "switch_type",
                endpointName: "16",
                lookup: {
                    toggle: 0,
                    momentary: 1,
                    multifunction: 2,
                    brightness_level: 3,
                    brightness_level_up: 4,
                    brightness_level_down: 5,
                    move_to_color_temperature: 6,
                    move_to_color_temperature_up: 7,
                    move_to_color_temperature_down: 8,
                    scene: 9,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "customSwitchType",
                description: "Switch type",
            }),
            m.enumLookup({
                name: "switch_type",
                endpointName: "17",
                lookup: {
                    toggle: 0,
                    momentary: 1,
                    multifunction: 2,
                    brightness_level: 3,
                    brightness_level_up: 4,
                    brightness_level_down: 5,
                    move_to_color_temperature: 6,
                    move_to_color_temperature_up: 7,
                    move_to_color_temperature_down: 8,
                    scene: 9,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "customSwitchType",
                description: "Switch type",
            }),
            m.enumLookup({
                name: "switch_type",
                endpointName: "18",
                lookup: {
                    toggle: 0,
                    momentary: 1,
                    multifunction: 2,
                    brightness_level: 3,
                    brightness_level_up: 4,
                    brightness_level_down: 5,
                    move_to_color_temperature: 6,
                    move_to_color_temperature_up: 7,
                    move_to_color_temperature_down: 8,
                    scene: 9,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "customSwitchType",
                description: "Switch type",
            }),
            m.enumLookup({
                name: "switch_type",
                endpointName: "19",
                lookup: {
                    toggle: 0,
                    momentary: 1,
                    multifunction: 2,
                    brightness_level: 3,
                    brightness_level_up: 4,
                    brightness_level_down: 5,
                    move_to_color_temperature: 6,
                    move_to_color_temperature_up: 7,
                    move_to_color_temperature_down: 8,
                    scene: 9,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "customSwitchType",
                description: "Switch type",
            }),
            m.enumLookup({
                name: "switch_type",
                endpointName: "20",
                lookup: {
                    toggle: 0,
                    momentary: 1,
                    multifunction: 2,
                    brightness_level: 3,
                    brightness_level_up: 4,
                    brightness_level_down: 5,
                    move_to_color_temperature: 6,
                    move_to_color_temperature_up: 7,
                    move_to_color_temperature_down: 8,
                    scene: 9,
                },
                cluster: "genOnOffSwitchCfg",
                attribute: "customSwitchType",
                description: "Switch type",
            }),
            m.commandsScenes({
                endpointNames: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            }),
            m.numeric({
                name: "scene_id",
                endpointNames: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
                access: "ALL",
                cluster: "genScenes",
                attribute: "customSceneId",
                valueMin: 0,
                valueMax: 255,
                description: "Scene ID",
            }),
            m.numeric({
                name: "group_id",
                endpointNames: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
                access: "ALL",
                cluster: "genScenes",
                attribute: "customGroupId",
                valueMin: 0,
                valueMax: 65527,
                description: "Group ID for scenes",
            }),
            m.numeric({
                name: "min_level",
                endpointNames: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
                access: "ALL",
                cluster: "genLevelCtrl",
                attribute: "minLevel",
                valueMin: 1,
                valueMax: 255,
                description: "Minimum level when decreasing",
            }),
            m.numeric({
                name: "max_level",
                endpointNames: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
                access: "ALL",
                cluster: "genLevelCtrl",
                attribute: "maxLevel",
                valueMin: 1,
                valueMax: 255,
                description: "Maximum level when increasing",
            }),
        ],
        meta: {},
        ota: true,
};
